### ISSUE TITLE
Problem connecting to hosts other than 'localhost'

### ISSUE THREAD

**Issue by sf-nika** [pakerfeldt/node-modbus-rest#2]
Not pointing to the socketOptions object:

https://github.com/pakerfeldt/node-modbus-rest/blob/86c34cd20c809997f108c272f1670700329aee10/lib/modbus.js#L38

suggested fix:
```js
connection: new h5Modbus.TcpConnection({ socketOptions: { host: host, port: port }}),
```

**Comment by pakerfeldt** [comment]
Fixed, thanks for the report.
