### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by grigals** [pakerfeldt/node-modbus-rest#4]
Hi @pakerfeldt,

Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license):

[...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

I hope [MIT](https://opensource.org/license/mit/) would be suitable. 

Thanks!

**Comment by pakerfeldt** [comment]
Sure thing, I can do that.

**Comment by pakerfeldt** [comment]
MIT license file added. Have a nice day!

**Comment by grigals** [comment]
Thanks @pakerfeldt!
